# Generated by Django 4.1.4 on 2022-12-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('less_app', '0003_school_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hour', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='less_app.course'),
        ),
    ]
